### ISSUE TITLE
关于daocloud 的https问题

### ISSUE THREAD

**Issue by MeowCold** [xw-hjl/Docker-Ghost#2]
您好，看到您的这个项目我现在也在使用daocloud。daocloud现在支持https证书上传了，测试后发现部分链接（首页header部分依旧为http）不知道这个项目有没有解决方法？

**Comment by xw-hjl** [comment]
只要在这两个地方把http改成https就可以实现全局ssl

![](https://hjl.daoapp.io/picture/20160909_230903.png)

![](https://hjl.daoapp.io/picture/20160909_230918.png)
